LongName: Southern Illinois University Edwardsville OpenStack
Description: SIUE Shared Openstack Cluster

ID: 10276

AddressLine1: SIUE State Route 157
City: Edwardsville

Country: USA
State: Illinois
Zipcode: "62026"


Latitude: 38.7931
Longitude: -89.9961
